# Cf. http://docs.travis-ci.com/user/getting-started/
# Cf. http://docs.travis-ci.com/user/languages/go/

language: go

go:
  - 1.4.2
  - tip

before_install:
  - sudo apt-get install -qq fuse

# Use the virtualized Trusty beta Travis is running in order to get fuse support.
# Cf. Personal communication from support@travis-ci.com.
dist: trusty
